name: Azure Web App - Node.js CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod

env:
  NODE_VERSION: '20.x'
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  ORG_CODE: 'nl'
  PROJECT_NAME: 'content-creation'
  REGION_CODE: 'euw'
  LOCATION: 'westeurope'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install, build, and test
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
          pnpm test

      - name: Zip artifact for deployment
        run: zip -r node-app.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app.zip

  infrastructure:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: build
    environment: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - uses: actions/checkout@v4

      - name: Generate Resource Names
        id: generate-names
        run: |
          chmod +x ./infra/naming.sh
          while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done < <(./infra/naming.sh ${{ github.event.inputs.environment || 'dev' }} ${{ env.LOCATION_CODE }} ${{ env.PROJECT_NAME }})

      - name: Azure Login
        uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        uses: azure/cli@4db43908b9df2e7ac93c8275a8f9a448c59338dd # v1
        with:
          inlineScript: |
            az group create --name ${{ env.RESOURCE_GROUP }} --location ${{ env.LOCATION }}

      - name: Deploy Bicep template
        uses: azure/arm-deploy@65ae74fb7aec7c680c88ef456811f353adae4d06 # v1
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ./infra/main.bicep
          parameters: >
            org=${{ env.ORG_CODE }}
            env=${{ github.event.inputs.environment || 'dev' }}
            project=${{ env.PROJECT_NAME }}
            region=${{ env.REGION_CODE }}
            location=${{ env.LOCATION }}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: infrastructure
    environment:
      name: ${{ github.event.inputs.environment || 'dev' }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip node-app.zip

      - name: Azure Login
        uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Generate Resource Names
        id: generate-names
        run: |
          chmod +x ./infra/naming.sh
          while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done < <(./infra/naming.sh ${{ env.ORG_CODE }} ${{ github.event.inputs.environment || 'dev' }} ${{ env.PROJECT_NAME }} ${{ env.REGION_CODE }})

      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@657f0700ea5214d56a0400d8ac5e8023c963d25d # v3
        with:
          app-name: ${{ env.APP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
